// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"database/sql"
	"time"
)

type Persona struct {
	IdPersona   int32     `json:"idpersona"`
	Nombre      string    `json:"nombre"`
	Apellido1   string    `json:"apellido_1"`
	Apellido2   string    `json:"apellido_2"`
	FechaNac    time.Time `json:"fechanac"`
	Direccion   string    `json:"direccion"`
	Telefono    string    `json:"telefono"`
	Correo      string    `json:"correo"`
}

type Detallefactura struct {
	Iddetallefactura int32           `json:"iddetallefactura"`
	Factura          int32           `json:"factura"`
	Tour             int32           `json:"tour"`
	Canttour         int32           `json:"canttour"`
	Preciotour       float64         `json:"preciotour"`
	Descuento        sql.NullFloat64 `json:"descuento"`
	Subtotal         float64         `json:"subtotal"`
	DetalleReserva   sql.NullInt32   `json:"detalleReserva"`
}

type Detallereserva struct {
	Iddetalle    int32         `json:"iddetalle"`
	Reserva      int32         `json:"reserva"`
	Fecha        string        `json:"fecha"`
	Hora         string        `json:"hora"`
	Tour         int32         `json:"tour"`
	Cantpersonas int32         `json:"cantpersonas"`
	Precio       float64       `json:"precio"`
	Descuento    float64       `json:"descuento"`
	Subtotal     float64       `json:"subtotal"`
}

type Factura struct {
	Idfactura     int32     `json:"idfactura"`
	Persona       int32     `json:"persona"`
	Reserva       int32     `json:"reserva"`
	Estadofactura string    `json:"estadofactura"`
	Fechafactura  time.Time `json:"fechafactura"`
	Metodopago    string    `json:"metodopago"`
	Iva           float64   `json:"iva"`
	Subtotal      float64   `json:"subtotal"`
	Total         float64   `json:"total"`
}

type Reserva struct {
	Numreserva    int32     `json:"numreserva"`
	Usuario       string    `json:"usuario"`
	Huesped       int32     `json:"huesped"`
	Estadoreserva string    `json:"estadoreserva"`
	Fechareserva  time.Time `json:"fechareserva"`
	Subtotal      float64   `json:"subtotal"`
	Impuesto      float64   `json:"impuesto"`
	Total         float64   `json:"total"`
}

type Tour struct {
	Idtour         int32   `json:"idtour"`
	Nombre         string  `json:"nombre"`
	Descripcion    string  `json:"descripcion"`
	Tipo           string  `json:"tipo"`
	Disponibilidad int8    `json:"disponibilidad"`
	Preciobase     float64 `json:"preciobase"`
	Ubicacion      string  `json:"ubicacion"`
	Imagetour      string  `json:"imagetour"`
}

type Usuario struct {
	Username  string         `json:"username"`
	Password  string         `json:"password"`
	Idpersona int32          `json:"idpersona"`
	Rol       string         `json:"rol"`
	Image     sql.NullString `json:"image"`
}
