// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dto

import (
	"database/sql"
	"time"
)

// Estructura para respaldo de base de datos
type RespaldoRequest struct {
	RutaRespaldo     string `json:"ruta_respaldo" binding:"required"`
	UsuarioEjecutor  string `json:"usuario_ejecutor" binding:"required"`
	Descripcion      string `json:"descripcion,omitempty"`
}

// Estructura para restauración de base de datos
type RestaurarRequest struct {
	RutaRespaldo     string `json:"ruta_respaldo" binding:"required"`
	UsuarioEjecutor  string `json:"usuario_ejecutor" binding:"required"`
	Descripcion      string `json:"descripcion,omitempty"`
}

// Estructura para listar respaldos
type ListarRespaldosRequest struct {
	RutaRespaldos string `json:"ruta_respaldos" binding:"required"`
}

// Estructura de respuesta para respaldo
type RespaldoResponse struct {
	Resultado           string    `json:"resultado"`
	ArchivoRespaldo     string    `json:"archivo_respaldo,omitempty"`
	Timestamp           string    `json:"timestamp,omitempty"`
	UsuarioEjecutor     string    `json:"usuario_ejecutor"`
	FechaRespaldo       time.Time `json:"fecha_respaldo"`
	Mensaje             string    `json:"mensaje"`
	TiempoEjecucionMs   int       `json:"tiempo_ejecucion_ms"`
	MensajeError        string    `json:"mensaje_error,omitempty"`
	FechaError          time.Time `json:"fecha_error,omitempty"`
}

// Estructura de respuesta para restauración
type RestaurarResponse struct {
	Resultado           string    `json:"resultado"`
	ArchivoRestaurado   string    `json:"archivo_restaurado,omitempty"`
	UsuarioEjecutor     string    `json:"usuario_ejecutor"`
	FechaRestauracion   time.Time `json:"fecha_restauracion"`
	Mensaje             string    `json:"mensaje"`
	TiempoEjecucionMs   int       `json:"tiempo_ejecucion_ms"`
	MensajeError        string    `json:"mensaje_error,omitempty"`
	FechaError          time.Time `json:"fecha_error,omitempty"`
}

// Estructura de respuesta para listar respaldos
type ListarRespaldosResponse struct {
	Resultado           string    `json:"resultado"`
	Respaldos           []RespaldoInfo `json:"respaldos,omitempty"`
	Mensaje             string    `json:"mensaje"`
	TiempoEjecucionMs   int       `json:"tiempo_ejecucion_ms"`
	MensajeError        string    `json:"mensaje_error,omitempty"`
	FechaError          time.Time `json:"fecha_error,omitempty"`
}

// Estructura para información de respaldo individual
type RespaldoInfo struct {
	NombreArchivo     string  `json:"nombre_archivo"`
	FechaModificacion time.Time `json:"fecha_modificacion"`
	TamañoBytes       int64   `json:"tamaño_bytes"`
	TamañoMB          float64 `json:"tamaño_mb"`
}

// Estructura para auditoría DBA
type AuditoriaDBA struct {
	IdAuditoriaDBA     int32          `json:"id_auditoria_dba"`
	UsuarioEjecutor    string         `json:"usuario_ejecutor"`
	TipoOperacion      string         `json:"tipo_operacion"`
	ArchivoRespaldo    sql.NullString `json:"archivo_respaldo"`
	Descripcion        sql.NullString `json:"descripcion"`
	Resultado          string         `json:"resultado"`
	Mensaje            sql.NullString `json:"mensaje"`
	TamañoArchivo      sql.NullInt64  `json:"tamaño_archivo"`
	FechaOperacion     time.Time      `json:"fecha_operacion"`
	IpAddress          string         `json:"ip_address"`
	UserAgent          sql.NullString `json:"user_agent"`
	TiempoEjecucionMs  sql.NullInt32  `json:"tiempo_ejecucion_ms"`
}

// AuditoriaDBAResponse estructura para respuesta JSON limpia
type AuditoriaDBAResponse struct {
	IdAuditoriaDBA         int32   `json:"id_auditoria_dba"`
	UsuarioEjecutor        string  `json:"usuario_ejecutor"`
	TipoOperacion          string  `json:"tipo_operacion"`
	ArchivoRespaldo        *string `json:"archivo_respaldo,omitempty"`
	Descripcion            *string `json:"descripcion,omitempty"`
	Resultado              string  `json:"resultado"`
	Mensaje                *string `json:"mensaje,omitempty"`
	TamañoArchivo          *int64  `json:"tamaño_archivo,omitempty"`
	TamañoMB               *float64 `json:"tamaño_mb,omitempty"`
	FechaOperacion         time.Time `json:"fecha_operacion"`
	IpAddress              string  `json:"ip_address"`
	UserAgent              *string `json:"user_agent,omitempty"`
	TiempoEjecucionMs      *int32  `json:"tiempo_ejecucion_ms,omitempty"`
	MinutosDesdeOperacion  *int32  `json:"minutos_desde_operacion,omitempty"`
	HorasDesdeOperacion    *int32  `json:"horas_desde_operacion,omitempty"`
	DiasDesdeOperacion     *int32  `json:"dias_desde_operacion,omitempty"`
}

// ToResponse convierte AuditoriaDBA a AuditoriaDBAResponse
func (a AuditoriaDBA) ToResponse() AuditoriaDBAResponse {
	response := AuditoriaDBAResponse{
		IdAuditoriaDBA:  a.IdAuditoriaDBA,
		UsuarioEjecutor: a.UsuarioEjecutor,
		TipoOperacion:   a.TipoOperacion,
		Resultado:       a.Resultado,
		FechaOperacion:  a.FechaOperacion,
		IpAddress:       a.IpAddress,
	}

	if a.ArchivoRespaldo.Valid {
		response.ArchivoRespaldo = &a.ArchivoRespaldo.String
	}
	if a.Descripcion.Valid {
		response.Descripcion = &a.Descripcion.String
	}
	if a.Mensaje.Valid {
		response.Mensaje = &a.Mensaje.String
	}
	if a.TamañoArchivo.Valid {
		response.TamañoArchivo = &a.TamañoArchivo.Int64
	}
	if a.UserAgent.Valid {
		response.UserAgent = &a.UserAgent.String
	}
	if a.TiempoEjecucionMs.Valid {
		response.TiempoEjecucionMs = &a.TiempoEjecucionMs.Int32
	}

	return response
}

// AuditoriaDBAFromView estructura para datos de la vista
type AuditoriaDBAFromView struct {
	IdAuditoriaDBA         int32          `json:"id_auditoria_dba"`
	UsuarioEjecutor        string         `json:"usuario_ejecutor"`
	TipoOperacion          string         `json:"tipo_operacion"`
	ArchivoRespaldo        sql.NullString `json:"archivo_respaldo"`
	Descripcion            sql.NullString `json:"descripcion"`
	Resultado              string         `json:"resultado"`
	Mensaje                sql.NullString `json:"mensaje"`
	TamañoArchivo          sql.NullInt64  `json:"tamaño_archivo"`
	TamañoMB               sql.NullFloat64 `json:"tamaño_mb"`
	FechaOperacion         time.Time      `json:"fecha_operacion"`
	IpAddress              string         `json:"ip_address"`
	UserAgent              sql.NullString `json:"user_agent"`
	TiempoEjecucionMs      sql.NullInt32  `json:"tiempo_ejecucion_ms"`
	MinutosDesdeOperacion  sql.NullInt32  `json:"minutos_desde_operacion"`
	HorasDesdeOperacion    sql.NullInt32  `json:"horas_desde_operacion"`
	DiasDesdeOperacion     sql.NullInt32  `json:"dias_desde_operacion"`
}

// ToResponse convierte AuditoriaDBAFromView a AuditoriaDBAResponse
func (a AuditoriaDBAFromView) ToResponse() AuditoriaDBAResponse {
	response := AuditoriaDBAResponse{
		IdAuditoriaDBA:  a.IdAuditoriaDBA,
		UsuarioEjecutor: a.UsuarioEjecutor,
		TipoOperacion:   a.TipoOperacion,
		Resultado:       a.Resultado,
		FechaOperacion:  a.FechaOperacion,
		IpAddress:       a.IpAddress,
	}

	if a.ArchivoRespaldo.Valid {
		response.ArchivoRespaldo = &a.ArchivoRespaldo.String
	}
	if a.Descripcion.Valid {
		response.Descripcion = &a.Descripcion.String
	}
	if a.Mensaje.Valid {
		response.Mensaje = &a.Mensaje.String
	}
	if a.TamañoArchivo.Valid {
		response.TamañoArchivo = &a.TamañoArchivo.Int64
	}
	if a.TamañoMB.Valid {
		response.TamañoMB = &a.TamañoMB.Float64
	}
	if a.UserAgent.Valid {
		response.UserAgent = &a.UserAgent.String
	}
	if a.TiempoEjecucionMs.Valid {
		response.TiempoEjecucionMs = &a.TiempoEjecucionMs.Int32
	}
	if a.MinutosDesdeOperacion.Valid {
		response.MinutosDesdeOperacion = &a.MinutosDesdeOperacion.Int32
	}
	if a.HorasDesdeOperacion.Valid {
		response.HorasDesdeOperacion = &a.HorasDesdeOperacion.Int32
	}
	if a.DiasDesdeOperacion.Valid {
		response.DiasDesdeOperacion = &a.DiasDesdeOperacion.Int32
	}

	return response
}

// Estructura para historial de respaldos
type HistorialRespaldos struct {
	IdHistorial        int32          `json:"id_historial"`
	ArchivoRespaldo    string         `json:"archivo_respaldo"`
	RutaCompleta       string         `json:"ruta_completa"`
	TamañoArchivo      int64          `json:"tamaño_archivo"`
	FechaCreacion      time.Time      `json:"fecha_creacion"`
	FechaModificacion  time.Time      `json:"fecha_modificacion"`
	UsuarioCreador     string         `json:"usuario_creador"`
	Descripcion        sql.NullString `json:"descripcion"`
	Estado             string         `json:"estado"`
	HashArchivo        sql.NullString `json:"hash_archivo"`
}

// =============================================
// FUNCIONES PARA PROCEDIMIENTOS ALMACENADOS
// =============================================
// IMPORTANTE: 
// - sp_respaldo_reservas_tour y sp_listar_respaldos_reservas_tour están en la base de datos reservas_tour
// - sp_restaurar_reservas_tour está en la base de datos master
// =============================================

// CrearRespaldo ejecuta el procedimiento almacenado sp_respaldo_reservas_tour
func CrearRespaldo(db *sql.DB, rutaRespaldo, usuarioEjecutor, descripcion string) (*RespaldoResponse, error) {
	var resultado RespaldoResponse
	
	err := db.QueryRow(
		"EXEC sp_respaldo_reservas_tour @ruta_respaldo, @usuario_ejecutor, @descripcion",
		sql.Named("ruta_respaldo", rutaRespaldo),
		sql.Named("usuario_ejecutor", usuarioEjecutor),
		sql.Named("descripcion", descripcion),
	).Scan(
		&resultado.Resultado,
		&resultado.ArchivoRespaldo,
		&resultado.Timestamp,
		&resultado.UsuarioEjecutor,
		&resultado.FechaRespaldo,
		&resultado.Mensaje,
		&resultado.TiempoEjecucionMs,
	)

	if err != nil {
		// Si hay error, intentar obtener información del error
		var errorResult RespaldoResponse
		errorErr := db.QueryRow(
			"EXEC sp_respaldo_reservas_tour @ruta_respaldo, @usuario_ejecutor, @descripcion",
			sql.Named("ruta_respaldo", rutaRespaldo),
			sql.Named("usuario_ejecutor", usuarioEjecutor),
			sql.Named("descripcion", descripcion),
		).Scan(
			&errorResult.Resultado,
			&errorResult.MensajeError,
			&errorResult.UsuarioEjecutor,
			&errorResult.FechaError,
			&errorResult.TiempoEjecucionMs,
		)

		if errorErr != nil {
			return nil, err
		}

		return &errorResult, nil
	}

	return &resultado, nil
}

// RestaurarBaseDatos ejecuta el procedimiento almacenado sp_restaurar_reservas_tour desde master
func RestaurarBaseDatos(db *sql.DB, rutaRespaldo, usuarioEjecutor, descripcion string) (*RestaurarResponse, error) {
	var resultado RestaurarResponse

	// Ejecutar el procedimiento almacenado
	// El procedimiento devuelve 6 columnas en caso exitoso y 5 en caso de error
	// Primero intentamos con 6 columnas (caso exitoso)
	err := db.QueryRow(
		"EXEC [master].[dbo].[sp_restaurar_reservas_tour] @ruta_respaldo, @usuario_ejecutor, @descripcion",
		sql.Named("ruta_respaldo", rutaRespaldo),
		sql.Named("usuario_ejecutor", usuarioEjecutor),
		sql.Named("descripcion", descripcion),
	).Scan(
		&resultado.Resultado,
		&resultado.ArchivoRestaurado,
		&resultado.UsuarioEjecutor,
		&resultado.FechaRestauracion,
		&resultado.Mensaje,
		&resultado.TiempoEjecucionMs,
	)

	if err != nil {
		// Si falla con 6 columnas, intentar con 5 columnas (caso de error)
		var errorResult RestaurarResponse
		errorErr := db.QueryRow(
			"EXEC [master].[dbo].[sp_restaurar_reservas_tour] @ruta_respaldo, @usuario_ejecutor, @descripcion",
			sql.Named("ruta_respaldo", rutaRespaldo),
			sql.Named("usuario_ejecutor", usuarioEjecutor),
			sql.Named("descripcion", descripcion),
		).Scan(
			&errorResult.Resultado,
			&errorResult.MensajeError,
			&errorResult.UsuarioEjecutor,
			&errorResult.FechaError,
			&errorResult.TiempoEjecucionMs,
		)

		if errorErr != nil {
			// Si ambos fallan, retornar error genérico
			return &RestaurarResponse{
				Resultado:        "ERROR",
				MensajeError:     err.Error(),
				UsuarioEjecutor:  usuarioEjecutor,
				FechaError:       time.Now(),
				TiempoEjecucionMs: 0,
			}, err
		}

		return &errorResult, nil
	}

	return &resultado, nil
}

// ListarRespaldos ejecuta el procedimiento almacenado sp_listar_respaldos_reservas_tour
func ListarRespaldos(db *sql.DB, rutaRespaldos string) ([]RespaldoInfo, error) {
	rows, err := db.Query(
		"EXEC sp_listar_respaldos_reservas_tour @ruta_respaldos",
		sql.Named("ruta_respaldos", rutaRespaldos),
	)

	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var respaldos []RespaldoInfo
	for rows.Next() {
		var respaldo RespaldoInfo
		err := rows.Scan(
			&respaldo.NombreArchivo,
			&respaldo.FechaModificacion,
			&respaldo.TamañoBytes,
			&respaldo.TamañoMB,
		)
		if err != nil {
			return nil, err
		}
		respaldos = append(respaldos, respaldo)
	}

	// Verificar errores de iteración
	if err = rows.Err(); err != nil {
		return nil, err
	}

	return respaldos, nil
}

// RestaurarBaseDatosConConexionMaster ejecuta el procedimiento usando una conexión específica a master
func RestaurarBaseDatosConConexionMaster(masterDB *sql.DB, rutaRespaldo, usuarioEjecutor, descripcion string) (*RestaurarResponse, error) {
	var resultado RestaurarResponse
	
	// Primero intentamos con 6 columnas (caso exitoso)
	err := masterDB.QueryRow(
		"EXEC sp_restaurar_reservas_tour @ruta_respaldo, @usuario_ejecutor, @descripcion",
		sql.Named("ruta_respaldo", rutaRespaldo),
		sql.Named("usuario_ejecutor", usuarioEjecutor),
		sql.Named("descripcion", descripcion),
	).Scan(
		&resultado.Resultado,
		&resultado.ArchivoRestaurado,
		&resultado.UsuarioEjecutor,
		&resultado.FechaRestauracion,
		&resultado.Mensaje,
		&resultado.TiempoEjecucionMs,
	)

	if err != nil {
		// Si falla con 6 columnas, intentar con 5 columnas (caso de error)
		var errorResult RestaurarResponse
		errorErr := masterDB.QueryRow(
			"EXEC sp_restaurar_reservas_tour @ruta_respaldo, @usuario_ejecutor, @descripcion",
			sql.Named("ruta_respaldo", rutaRespaldo),
			sql.Named("usuario_ejecutor", usuarioEjecutor),
			sql.Named("descripcion", descripcion),
		).Scan(
			&errorResult.Resultado,
			&errorResult.MensajeError,
			&errorResult.UsuarioEjecutor,
			&errorResult.FechaError,
			&errorResult.TiempoEjecucionMs,
		)

		if errorErr != nil {
			// Si ambos fallan, retornar error genérico
			return &RestaurarResponse{
				Resultado:        "ERROR",
				MensajeError:     err.Error(),
				UsuarioEjecutor:  usuarioEjecutor,
				FechaError:       time.Now(),
				TiempoEjecucionMs: 0,
			}, err
		}

		return &errorResult, nil
	}

	return &resultado, nil
}

// ObtenerAuditoriaDBA obtiene el historial de auditoría DBA con paginación usando vista
func ObtenerAuditoriaDBA(db *sql.DB, limit, offset int) ([]AuditoriaDBAResponse, error) {
	query := `
		SELECT 
			idAuditoriaDBA,
			usuario_ejecutor,
			tipo_operacion,
			archivo_respaldo,
			descripcion,
			resultado,
			mensaje,
			tamaño_archivo,
			tamaño_mb,
			fecha_operacion,
			ip_address,
			user_agent,
			tiempo_ejecucion_ms,
			minutos_desde_operacion,
			horas_desde_operacion,
			dias_desde_operacion
		FROM v_auditoria_dba 
		ORDER BY fecha_operacion DESC
		OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY
	`

	rows, err := db.Query(query, sql.Named("offset", offset), sql.Named("limit", limit))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var auditorias []AuditoriaDBAFromView
	for rows.Next() {
		var auditoria AuditoriaDBAFromView
		err := rows.Scan(
			&auditoria.IdAuditoriaDBA,
			&auditoria.UsuarioEjecutor,
			&auditoria.TipoOperacion,
			&auditoria.ArchivoRespaldo,
			&auditoria.Descripcion,
			&auditoria.Resultado,
			&auditoria.Mensaje,
			&auditoria.TamañoArchivo,
			&auditoria.TamañoMB,
			&auditoria.FechaOperacion,
			&auditoria.IpAddress,
			&auditoria.UserAgent,
			&auditoria.TiempoEjecucionMs,
			&auditoria.MinutosDesdeOperacion,
			&auditoria.HorasDesdeOperacion,
			&auditoria.DiasDesdeOperacion,
		)
		if err != nil {
			return nil, err
		}
		auditorias = append(auditorias, auditoria)
	}

	// Verificar errores de iteración
	if err = rows.Err(); err != nil {
		return nil, err
	}

	// Convertir a respuesta limpia
	var responses []AuditoriaDBAResponse
	for _, auditoria := range auditorias {
		responses = append(responses, auditoria.ToResponse())
	}

	return responses, nil
}

